recruit:
  drivePath: /temp/recruit/resume
  mail:
    fromAddress: ositechportal@gmail.com
    toAddress: ositechportal@gmail.com
    username: ositechportal@gmail.com
    password: ENC(HJsSzPsTbQIuQ9PhY5WOZSviVcXnreJ/) #123osi123
    host: smtp.gmail.com
    templet:
        SRC_INTERVIEW_FEEDBACK_FORM: OSI_Interview_Feedback_Form.doc
        SRC_INTERVIEWER_VM: interviewer.vm
        SRC_CANDIDATE_VM: candidate.vm
        SRC_FEEDBACK_HR_VM: feedback_hr.vm
        SRC_JOB_REQUISITION_VM: jobRequisition.vm
        SRC_CANCELINTERVIEW_VM: cancelInterview.vm
        SRC_POST_REF_JOB_VM: postref_job.vm
        SRC_APPROVE_REQUISITION_VM: approveRequisitionNotification.vm
        SRC_OFFER_TO_BE_APPROVED_VM: offerToBeApprove.vm
        SRC_OFFER_VM: offer.vm

logging:
  level:
      org.springframework.web: DEBUG
      com.osi.its: DEBUG
  file: /temp/recruit/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # Logging pattern for file
  
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    algorithm: pbewithmd5anddes
    
spring:
  application:
    name: irecruit-service
  data:
    mongodb:
      repositories:
        enabled: true
      database: osirpdb
      host: localhost
      port: 27017
      
#      uri: mongodb://127.0.0.1:27017/osirpdb
#    redis:
#      repositories:
#        enabled: false
    elasticsearch:
        repositories:
           enabled: false
        cluster-name: irecruitsearch
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: secret
  mail:
    host: smtp.gmail.com
    port: 25
    username: ositechportal@gmail.com
    password: ENC(HJsSzPsTbQIuQ9PhY5WOZSviVcXnreJ/) #123osi123

server:
  context-path: /irecruit-service-phase1
  port: 7080
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
  require-ssl: false
